apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: upm
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: poke-app/k8s/practica-front
    repoURL: 'https://github.com/looreenaaaa/taller-kubernetes-II'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      enabled: true
