apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: practica-front
  template:
    metadata:
      labels:
        app: practica-front
    spec:
      containers:
        - name: practica-front
          image: practica-hello-world:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 10