apiVersion: v1
kind: Service
metadata:
  name: practica-front-service
  namespace: hello-world
spec:
  selector:
    app: practica-front-service
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP